### ISSUE TITLE
If you want to make it more user friendly

### ISSUE THREAD

**Issue by mariomadproductions** [exelix11/TheFourthDimension#1]
You may want to refer to these editors:
SM64DSe
Whitehole

Whitehole is for Galaxy, which uses similar files to 3D Land.

Also, Ohana3DS has better model rendering than EFE it seems. So if you may want to use it's code rather than EFE's. (There are also official programs, but you probably don't want to use those because of legal issues. And they might not be very good)

**Comment by mariomadproductions** [comment]
If you make an object xml/database like those editors, I will be willing to research object function/parameters. I have HANS, and it appears to work with 3D Land for me.

Do you want specific suggestions about usability?

**Comment by exelix11** [comment]
I choiced EFE to convert models because was the fastest way to do that, i just had to import the dlls, maybe i'll move to Ohana.
For now i use the "CreatorClassNameTable" as object database, since it contains the list of every object in the game, would be nice to have a sort of documentation about using objects, i'll look into that

**Comment by mariomadproductions** [comment]
That's what I meant: extended documentation. Using existing lists is a good idea, as it makes the job easier :P
